# Generated by Django 5.0 on 2023-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='street',
            field=models.CharField(default=99, max_length=100),
            preserve_default=False,
        ),
    ]
