# Generated by Django 5.0 on 2024-01-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdata_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
