# Generated by Django 5.0 on 2024-02-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdata_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='billno',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
