# Generated by Django 5.0 on 2024-02-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdata_billno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='billno',
            new_name='bill_id',
        ),
    ]
